namespace OwlDomain.ParsingTools.Syntax;

partial struct SyntaxKind
{
	#region Properties
	/// <summary>Represents a syntax kind for the token that represents the end of the input.</summary>
	public static SyntaxKind EndOfInput { get; } = new("end_of_input");

	/// <summary>Represents a syntax kind for a collection of invalid characters that have been converted to a trivia node.</summary>
	public static SyntaxKind BadCharactersTrivia { get; } = new("bad_characters", SyntaxCategory.Trivia);

	/// <summary>Represents a syntax kind for invalid syntax nodes that would've been skipped by the parser because they have no place in a valid syntax tree.</summary>
	/// <remarks>This trivia node exists to ensure that even invalid syntax is still retained in the tree. Generated by a parser.</remarks>
	public static SyntaxKind BadSyntax { get; } = new("bad_syntax", SyntaxCategory.Trivia);

	/// <summary>Represents a syntax kind for indentation trivia.</summary>
	public static SyntaxKind Indentation { get; } = new("indentation", SyntaxCategory.Trivia);

	/// <summary>Represents a syntax kind for line break trivia.</summary>
	public static SyntaxKind LineBreak { get; } = new("line_break", SyntaxCategory.Trivia);
	#endregion
}
