using System.IO;
using System.Web;
using OwlDomain.Owl.Code.CodeAnalysis.ControlFlow.Blocks;
using OwlDomain.Owl.Code.CodeAnalysis.ControlFlow.Branches;
using OwlDomain.Owl.Code.CodeAnalysis.ControlFlow.Graphs;
using OwlDomain.ParsingTools.Syntax.Printing;

namespace OwlDomain.Owl.Code.CodeAnalysis.ControlFlow.Printing.Mermaid;

partial class MermaidControlFlow
{
	public sealed class Printer : ICustomisableControlFlowPrinter<Settings, Result>
	{
		#region Nested types
		public enum NodeKind
		{
			Rectangle, // [ ]
			Rounded, // ( )
			Stadium, // ([ ])
			Circle, // (( ))
			DoubleCircle, // ((( )))
			Rhombus, // { }
			Hexagon, // {{ }}
			Parallelogram, // [/ /]
			Parallelogram2, // [\ \]
		}
		public enum BranchKind
		{
			SingleArrow, // -->
		}
		public enum TextAlign
		{
			Left,
			Center,
			Right
		}

		public readonly struct BranchScope(Context context, string targetId) : IDisposable
		{
			#region Methods
			public void Dispose() => context.Printer.PrintBranchEnd(context, targetId);
			#endregion
		}
		public readonly struct ElementScope(Context context, string element) : IDisposable
		{
			#region Methods
			public void Dispose() => context.Printer.PrintElementEnd(context, element);
			#endregion
		}
		public readonly struct NodeScope(Context context, string suffix) : IDisposable
		{
			#region Methods
			public void Dispose() => context.Printer.PrintNodeEnd(context, suffix);
			#endregion
		}

		public enum CodeContext
		{
			Graph,
			StartHeader,
			EndHeader,
			SourceReference,
		}
		public readonly struct Context(
			Printer printer,
			IControlFlowGraph graph,
			Settings settings,
			IndentedTextWriter writer,
			CodeContext codeContext)
		{
			#region Properties
			public Printer Printer { get; } = printer;
			public IControlFlowGraph Graph { get; } = graph;
			public Settings Settings { get; } = settings;
			public IndentedTextWriter Writer { get; } = writer;
			public CodeContext CodeContext { get; } = codeContext;
			#endregion

			#region Methods
			public Context WithNewCodeContext(CodeContext codeContext)
			{
				return new(Printer, Graph, Settings, Writer, codeContext);
			}
			#endregion
		}
		#endregion

		#region Methods
		public Result Print(IControlFlowGraph graph, Settings settings)
		{
			if (settings.UseInlineCss is false)
				ThrowHelper.ThrowNotSupportedException("The Mermaid control printer doesn't support external css yet.");

			using (StringWriter stringWriter = new())
			using (IndentedTextWriter writer = new(stringWriter, "  "))
			{
				Context context = new(this, graph, settings, writer, CodeContext.Graph);

				PrintFrontMatter(context);
				PrintPreamble(context);

				DiagnosticSourceDisplay source = GetReferenceSource(context);

				if (settings.IncludePlainSource)
					PrintPlainSource(context, source.GetLines());

				writer.WriteLine();
				writer.WriteLine("flowchart TB;");

				using (writer.Indented())
				{
					PrintBlocks(context);
					PrintBranches(context);
				}

				if (settings.IncludeSourceReference)
					PrintReferenceSource(context, source);

				string code = stringWriter.ToString();
				string configCode = GetConfigCode(context);
				string styleCode = GetStyleCode(context);

				return new(graph, settings, code, configCode, styleCode);
			}
		}
		public string GetConfigCode(Context context)
		{
			return $"{{ \"maxTextSize\": {context.Settings.MaxTextSize} }}";
		}
		public string GetStyleCode(Context context)
		{
			return
$@"span:target {{
	scroll-margin-top: calc(50vh - 1em);
	border: 1px solid {context.Settings.Styles?.Get(ClassificationKind.Focus).Color?.ToHtml ?? "#red"};
	padding: 3px;
	margin: -4px;
}}";
		}
		public void PrintPreamble(Context context)
		{
			context.Writer.WriteLine("%% ");
			context.Writer.WriteLine("%% This is a control flow graph that was generated by the OWL compiler.");
			context.Writer.WriteLine("%% https://github.com/owl-whatever-language");
			context.Writer.WriteLine("%% ");

			string file = context.Graph.Node.GetTree().Source.SimpleName;

			if (context.Graph is IDocumentControlFlowGraph)
				context.Writer.WriteLine($"%% This particular CFG was generated from the main code in the {file} file.");
			else if (context.Graph is IFunctionControlFlowGraph function)
				context.Writer.WriteLine($"%% This particular CFG was generated for the '{function.Node.Function.Name}' function in the {file} file.");
			else
				context.Writer.WriteLine($"%% This particular CFG was generated from some part of the {file} file.");

			context.Writer.WriteLine("%% ");
		}
		public void PrintPlainSource(Context context, TextFragmentLineCollection source)
		{
			context.Writer.WriteLine("%% Since this file is most likely going to be very difficult to be human-readable,");
			context.Writer.WriteLine("%% here is a plain text version of the file for:");
			context.Writer.WriteLine("%% ");

			string tab = context.Settings.TabSize is null ? "\t" : new(' ', context.Settings.TabSize.Value);
			using (IndentedTextWriter writer = new(context.Writer, tab))
			{
				for (int i = 0; i < source.Count; i++)
				{
					TextFragmentLine line = source[i];

					if (line.Line is null)
						continue;

					writer.Write("%% ");
					line.WritePlainText(context.Writer);
					writer.WriteLine();
				}
			}

			context.Writer.WriteLine("%% ");
		}
		#endregion

		#region FrontMatter methods
		public void PrintTitle(Context context)
		{
			context.Writer.WriteLine("title: Control flow graph");
		}
		public void PrintFrontMatter(Context context)
		{
			context.Writer.WriteLine("---");
			PrintTitle(context);
			PrintConfig(context);
			context.Writer.WriteLine("---");
			context.Writer.WriteLine();
		}
		public void PrintConfig(Context context)
		{
			context.Writer.WriteLine("config:");
			using (context.Writer.Indented())
			{
				context.Writer.WriteLine($"maxTextSize: {context.Settings.MaxTextSize}");
				context.Writer.WriteLine("themeVariables:");
				using (context.Writer.Indented())
				{
					context.Writer.WriteLine("darkMode: true");
					context.Writer.WriteLine("fontFamily: 'Droid Sans Mono, monospace'");

					string? background = context.Settings.Styles?.Background?.ToHex;

					if (background is not null)
						context.Writer.WriteLine($"edgeLabelBackground: '{background}'");
				}
			}
		}
		#endregion

		#region Reference source methods
		public DiagnosticSourceDisplay GetReferenceSource(Context context)
		{
			IClassificationStyling styling = context.Settings.Styles ?? new ClassificationStyling();
			DiagnosticSourceDisplay display = new(context.Graph.Node.GetTree(), styling);

			void Relevant(params ReadOnlySpan<IAnnotatedSyntaxNode> nodes)
			{
				foreach (var node in nodes)
					display.MarkRelevant(node, shouldDim: false);
			}
			void Dimmed(params ReadOnlySpan<IAnnotatedSyntaxNode> nodes)
			{
				foreach (var node in nodes)
					display.MarkRelevant(node, shouldDim: true);
			}

			if (context.Graph is IFunctionControlFlowGraph function)
			{
				Dimmed(function.Node.Signature);

				if (function.Node.Body is IAnnotatedShortFunctionBodySyntax shortBody)
					Dimmed(shortBody.Arrow, shortBody.Terminator);
				else if (function.Node.Body is IAnnotatedBlockFunctionBodySyntax block)
					Dimmed(block.Block.Start, block.Block.End);
			}

			foreach (IControlFlowBlock block in context.Graph.Blocks)
			{
				if (block is IControlFlowExpressionBlock expression)
					Relevant(expression.Expression);
				else if (block is IControlFlowStatementBlock statement)
				{
					foreach (IAnnotatedStatementSyntax current in statement.Statements)
					{
						if (current.IsExecutable)
							Relevant(current);
					}
				}
				else if (block is IControlFlowConstructBlock construct)
				{
					if (construct.Node is IAnnotatedBlockStatementSyntax blockStatement)
						Dimmed(blockStatement.Start, blockStatement.End);
					else if (construct.Node is IAnnotatedWhileStatementSyntax @while)
					{
						Relevant(@while.Keyword);
						Dimmed(@while.Start, @while.End);
					}
					else if (construct.Node is IAnnotatedIfStatementSyntax @if)
					{
						Relevant(@if.Keyword);
						Dimmed(@if.Start, @if.End);
					}
					else if (construct.Node is IAnnotatedIfElseStatementSyntax ifElse)
					{
						Relevant(ifElse.Keyword, ifElse.Else);
						Dimmed(ifElse.Start, ifElse.End);
					}
				}
			}

			display.ApplyTypicalTransformations();
			return display;
		}
		public void PrintReferenceSource(Context context, DiagnosticSourceDisplay source)
		{
			TextFragmentLineCollection lines = source.GetLines();
			lines.PrefixLineMargin();
			source.ApplyDim();

			context = context.WithNewCodeContext(CodeContext.SourceReference);

			context.Writer.WriteLine();
			context.Writer.WriteLine("%% Source code reference");
			using (PrintNode(context, "source_code_reference", NodeKind.Rectangle))
			{
				TextFragment title = new("Source code reference", ClassificationKind.Keyword);
				TextFragment file = new(context.Graph.Node.GetTree().Source.SimpleName, ClassificationKind.File);
				TextFragmentLineCollection header = [new(null, title), new(null, file)];

				PrintCode(context, header, TextAlign.Center);
				context.Writer.WriteLine();
				PrintCode(context, lines);
			}
		}
		#endregion

		#region Branch methods
		public void PrintBranches(Context context)
		{
			PrintBranches(context, "Unconditional branches", b => b.HasCondition is false);
			PrintBranches(context, "Conditional branches", b => b.HasCondition);
		}
		public bool IncludeBranch(Context context, IControlFlowBidirectionalBranch branch)
		{
			if (context.Settings.Optimise is false)
				return true;

			return IncludeBlock(context, branch.From);
		}
		public void PrintBranches(Context context, string header, Predicate<IControlFlowBidirectionalBranch> predicate)
		{
			IReadOnlyList<IControlFlowBidirectionalBranch> branches = context.Graph.Branches
				.Where(predicate.Invoke)
				.Where(b => IncludeBranch(context, b))
				.ToArray();

			PrintBranches(context, header, branches);
		}
		public void PrintBranches(Context context, string header, IReadOnlyList<IControlFlowBidirectionalBranch> branches)
		{
			if (branches.Count is 0)
				return;

			context.Writer.WriteLine();
			context.Writer.WriteLine($"%% {header}");

			foreach (IControlFlowBidirectionalBranch branch in branches)
				PrintBranch(context, branch);
		}
		public void PrintBranch(Context context, IControlFlowBidirectionalBranch branch)
		{
			IControlFlowBlock target = GetTarget(context, branch);

			if (branch.HasCondition is false)
			{
				context.Writer.WriteLine($"{branch.From.Id} --> {target.Id}");
				return;
			}

			using (PrintBranch(context, branch.From.Id, target.Id, BranchKind.SingleArrow))
			{
				TextFragment value = new(branch.IsNegated ? "false" : "true", ClassificationKind.Boolean);
				TextFragmentLineCollection lines = [new(null, value)];
				PrintCode(context, lines);
			}
		}

		public BranchScope PrintBranch(Context context, string fromId, string targetId, BranchKind kind)
		{
			PrintBranchStart(context, fromId, kind);
			return new(context, targetId);
		}
		public BranchScope PrintBranch(Context context, string fromId, string targetId, string arrow)
		{
			PrintBranchStart(context, fromId, arrow);
			return new(context, targetId);
		}
		public void PrintBranchStart(Context context, string id, BranchKind kind)
		{
			string arrow = kind switch
			{
				BranchKind.SingleArrow => "-->",

				_ => ThrowHelper.ThrowArgumentException<string>(nameof(kind), $"Unsupported branch kind ({kind})."),
			};

			PrintBranchStart(context, id, arrow);
		}
		public void PrintBranchStart(Context context, string id, string arrow)
		{
			context.Writer.Write(id);
			context.Writer.Write(' ');
			context.Writer.Write(arrow);
			context.Writer.Write('|');
			context.Writer.Write('"');
		}
		public void PrintBranchEnd(Context context, string id)
		{
			context.Writer.Write('"');
			context.Writer.Write('|');
			context.Writer.WriteLine(id);
		}
		#endregion

		#region Block methods
		public void PrintBlocks(Context context)
		{
			context.Writer.WriteLine("");
			context.Writer.WriteLine("%% Start");
			PrintBlock(context, context.Graph.Start);

			context.Writer.WriteLine("");
			context.Writer.WriteLine("%% End");
			PrintBlock(context, context.Graph.End);

			PrintBlocks<IControlFlowStatementBlock>(context, "Statements");
			PrintBlocks<IControlFlowExpressionBlock>(context, "Expressions");
			PrintBlocks<IControlFlowConstructBlock>(context, "Constructs");
		}
		public bool IncludeBlock(Context context, IControlFlowBlock block)
		{
			if (block is IControlFlowConstructBlock construct)
			{
				if (construct.Expression is null)
					return false;

				if (construct.Expression.WillBranch)
					return true;

				return false;
			}

			if (block is IControlFlowMarkerBlock)
				return false;

			return true;
		}
		public void PrintBlocks<T>(Context context, string header) where T : notnull, IControlFlowBlock
		{
			IReadOnlyList<IControlFlowBlock> blocks = context.Graph.Blocks
				.Where(b => b is T && IncludeBlock(context, b))
				.ToArray();

			PrintBlocks(context, header, blocks);
		}
		public void PrintBlocks(Context context, string header, IReadOnlyList<IControlFlowBlock> blocks)
		{
			if (blocks.Count is 0)
				return;

			context.Writer.WriteLine();
			context.Writer.WriteLine($"%% {header}");

			foreach (IControlFlowBlock block in blocks)
				PrintBlock(context, block);
		}
		public void PrintBlock(Context context, IControlFlowBlock block)
		{
			if (block is IControlFlowStartBlock start)
				PrintBlock(context, start);
			else if (block is IControlFlowEndBlock end)
				PrintBlock(context, end);
			else if (block is IControlFlowExpressionBlock expression)
				PrintBlock(context, expression);
			else if (block is IControlFlowStatementBlock statement)
				PrintBlock(context, statement);
			else if (block is IControlFlowConstructBlock construct)
				PrintBlock(context, construct);
			else if (block is IControlFlowMarkerBlock marker)
				PrintBlock(context, marker);
			else
				ThrowHelper.ThrowArgumentException(nameof(block), $"Unsupported block type ({block.GetType().Name}).");
		}
		public void PrintBlock(Context context, IControlFlowStartBlock block)
		{
			context = context.WithNewCodeContext(CodeContext.StartHeader);
			using (PrintNode(context, block.Id, NodeKind.Rounded))
			{
				TextFragmentLineCollection header = [];

				TextFragment start = new("start", ClassificationKind.Keyword);
				header.AddLine(start);

				if (block.Graph is IDocumentControlFlowGraph document && document.Node.Tree is not null)
				{
					TextFragment file = new(document.Node.Tree.Source.SimpleName, ClassificationKind.File);
					header.AddLine(file);
				}

				PrintCode(context, header, TextAlign.Center);

				if (block.Graph is IFunctionControlFlowGraph function)
				{
					TextFragmentLineCollection signature = function.Node.Signature
						.GetLines()
						.TrimAll()
						.PrefixLineMargin();

					context.Writer.WriteLine();
					PrintCode(context, signature);
				}
			}
		}
		public void PrintBlock(Context context, IControlFlowEndBlock block)
		{
			context = context.WithNewCodeContext(CodeContext.EndHeader);
			using (PrintNode(context, block.Id, NodeKind.DoubleCircle))
			{
				TextFragment end = new("end", ClassificationKind.Keyword);
				TextFragmentLineCollection header = [];
				header.AddLine(end);

				PrintCode(context, header, TextAlign.Center);
			}
		}
		public void PrintBlock(Context context, IControlFlowExpressionBlock block)
		{
			using (PrintNode(context, block.Id, NodeKind.Rounded))
			{
				if (block.ConstructName is not null && (block.Expression.WillBranch is false))
				{
					// Note(Nightowl):
					// This assumes that the keyword will be the first thing in the parent;
					// Perhaps construct blocks should have a keyword token instead of a name?
					int line = block.Expression.Parent?.Position.Start.Line ?? block.Expression.Position.Start.Line;

					TextFragment name = new(block.ConstructName, ClassificationKind.Keyword);

					TextFragmentLineCollection nameLines = [new(line, name)];
					nameLines.PrefixLineMargin();

					PrintCode(context, nameLines, TextAlign.Center);
					// Note(Nightowl):
					// There might need to be a blank line here since the alignment
					// changes and that seems to mess things up but only sometimes?
				}

				TextFragmentLineCollection lines = block.Expression
					.GetLines()
					.TrimAll();

				PrintCode(context, lines);
			}
		}
		public void PrintBlock(Context context, IControlFlowStatementBlock block)
		{
			using (PrintNode(context, block.Id, NodeKind.Rectangle))
			{
				TextFragmentLineCollection lines = [];
				foreach (IAnnotatedStatementSyntax current in block.Statements)
					lines.AddRange(current.GetLines());

				lines
					.TrimAll()
					.PrefixLineMargin();

				PrintCode(context, lines);
			}
		}
		public void PrintBlock(Context context, IControlFlowConstructBlock block)
		{
			Debug.Assert(block.Expression is not null);
			using (PrintNode(context, block.Id, NodeKind.Rounded))
			{
				TextFragment name = new(block.Name, ClassificationKind.Keyword);

				TextFragmentLineCollection nameLines = [new(block.Node.Position.Start.Line, name)];
				nameLines.PrefixLineMargin();

				PrintCode(context, nameLines, TextAlign.Center);

				TextFragmentLineCollection lines = block
					.Expression
					.GetLines()
					.TrimAll();

				PrintCode(context, lines);
			}
		}
		public void PrintBlock(Context context, IControlFlowMarkerBlock block)
		{
			context.Writer.WriteLine("%% Marker blocks are not yet supported.");
		}
		#endregion

		#region Node methods
		public NodeScope PrintNode(Context context, string id, NodeKind kind)
		{
			(string prefix, string suffix) = kind switch
			{
				NodeKind.Rectangle => ("[", "]"), // ( )
				NodeKind.Rounded => ("(", ")"), // ( )
				NodeKind.Stadium => ("([", "])"), // ([ ])
				NodeKind.Circle => ("((", "))"), // (( ))
				NodeKind.DoubleCircle => ("(((", ")))"), // ((( )))
				NodeKind.Rhombus => ("{", "}"), // { }
				NodeKind.Hexagon => ("{{", "}}"), // {{ }}
				NodeKind.Parallelogram => ("[/", "/]"), // [/ /]
				NodeKind.Parallelogram2 => ("[\\", "\\]"), // [\ \]

				_ => ThrowHelper.ThrowArgumentException<(string, string)>(nameof(kind), $"Unknown node kind ({kind}).")
			};

			return PrintNode(context, id, prefix, suffix);
		}
		public NodeScope PrintNode(Context context, string id, string prefix, string suffix)
		{
			PrintNodeStart(context, id, prefix);
			return new(context, suffix);
		}
		public void PrintNodeStart(Context context, string id, string type)
		{
			context.Writer.Write(id);
			context.Writer.Write(type);
			context.Writer.Write('"');
		}
		public void PrintNodeEnd(Context context, string type)
		{
			context.Writer.Write('"');
			context.Writer.WriteLine(type);
		}
		#endregion

		#region Html methods
		public void PrintCode(Context context, TextFragmentLineCollection lines, TextAlign alignment = TextAlign.Left)
		{
			string alignmentValue = alignment switch
			{
				TextAlign.Left => "left",
				TextAlign.Center => "center",
				TextAlign.Right => "right",

				_ => ThrowHelper.ThrowArgumentException<string>(nameof(alignment), $"Unknown text alignment ({alignment}).")
			};

			List<string> styleParts =
			[
				"white-space:pre",
				$"text-align:{alignmentValue}"
			];

			if (context.Settings.TabSize is not null) // Note(Nightowl): Doesn't seem to always be respected?
				styleParts.Add($"tab-size:{context.Settings.TabSize}");

			if (context.Settings.IncludeLineNavigation)
				styleParts.Add($"margin:{context.Settings.LineNavigationPadding}px");

			string styleAttribute = $"style=\"{string.Join(';', styleParts)}\"";

			using (context.Writer.NoIndent())
			using (PrintElement(context, "div", [styleAttribute]))
				PrintCodeCore(context, lines);
		}
		public void PrintCodeCore(Context context, TextFragmentLineCollection lines)
		{
			for (int i = 0; i < lines.Count; i++)
			{
				TextFragmentLine line = lines[i];

				if (context.Settings.IncludeLineNavigation && context.CodeContext is CodeContext.SourceReference or CodeContext.Graph)
				{
					context.Writer.Write(' ');
					PrintLine(context, line);
					context.Writer.Write(' ');
				}
				else
					PrintLine(context, line);

				if (i + 1 < lines.Count)
					context.Writer.WriteLine();
			}
		}
		public void PrintLine(Context context, TextFragmentLine line)
		{
			bool isSimple =
				line.IsWhiteSpaceOrSourcePrefix ||
				line.IsOnlyCommented ||
				line.IsDimmed ||
				line.Line is null ||
				line.Count is 0 ||
				(context.Settings.IncludeLineData is false && context.Settings.IncludeLineNavigation is false);

			if (isSimple)
			{
				foreach (TextFragment fragment in line)
					PrintFragment(context, fragment);

				return;
			}

			Debug.Assert(line.Line is not null);
			Debug.Assert(line.Any());

			List<string> spanAttributes = [];

			if (context.Settings.IncludeLineData)
			{
				string attribute = GetLineDataAttribute(context, line.Line.Value);
				spanAttributes.Add(attribute);
			}

			if (context.Settings.IncludeLineNavigation)
			{
				string attribute = GetLineIdAttribute(context, line.Line.Value);
				spanAttributes.Add(attribute);
			}

			using (PrintElement(context, "span", spanAttributes))
			{
				foreach (TextFragment fragment in line)
				{
					if (TryGetLineLinkAttribute(context, fragment, out string? linkAttribute))
					{
						string styleAttribute = "style=\"text-decoration:none\"";

						using (PrintElement(context, "a", [linkAttribute, styleAttribute]))
							PrintFragment(context, fragment);
					}
					else
						PrintFragment(context, fragment);
				}
			}
		}
		public void PrintFragment(Context context, TextFragment fragment)
		{
			StyleInfo style = context.Settings.Styles?.Get(fragment.Classifications) ?? default;
			string value = EncodeValue(context, fragment.Text);

			List<string> attributes = [];

			if (style != default)
				attributes.Add(style.ToHtmlStyle);

			if (context.Settings.IncludeSymbolData && TryGetSymbolDataAttribute(context, fragment, out string? symbol))
				attributes.Add(symbol);

			if (attributes.Count is 0)
			{
				context.Writer.Write(value);
				return;
			}

			using (PrintElement(context, "span", attributes))
				context.Writer.Write(value);
		}
		public string EncodeValue(Context context, string value)
		{
			// Note(Nightowl): Because mermaid doesn't like semicolons;
			string[] parts = value.Split(';');

			for (int i = 0; i < parts.Length; i++)
				parts[i] = HttpUtility.HtmlEncode(parts[i]);

			string encoded = string.Join("&#x3b;", parts);

			// Note(Nightowl): Yet another thing that doesn't actually respect tab size, even though it's explicitly set;
			if (context.Settings.TabSize is not null)
			{
				string tabString = new(' ', context.Settings.TabSize.Value);
				encoded = encoded.Replace("\t", tabString);
			}

			return encoded;
		}
		#endregion

		#region Html element methods
		public ElementScope PrintElement(Context context, string element, IReadOnlyList<string> attributes)
		{
			PrintElementStart(context, element, attributes);
			return new(context, element);
		}
		public void PrintElementStart(Context context, string element, IReadOnlyList<string> attributes)
		{
			context.Writer.Write('<');
			context.Writer.Write(element);
			foreach (string attribute in attributes)
			{
				context.Writer.Write(' ');
				context.Writer.Write(attribute);
			}
			context.Writer.Write('>');
		}
		public void PrintElementEnd(Context context, string element)
		{
			context.Writer.Write("</");
			context.Writer.Write(element);
			context.Writer.Write('>');
		}
		#endregion

		#region Html attribute methods
		public string GetLineId(Context context, int line, bool isDeclaration)
		{
			if (isDeclaration)
				return $"line-source-{line}";

			return $"line-use-{line}";
		}
		public string GetLineIdAttribute(Context context, int line)
		{
			string id = GetLineId(context, line, context.CodeContext is CodeContext.SourceReference);
			return $"id=\"{id}\"";
		}
		public bool TryGetLineLinkAttribute(Context context, TextFragment fragment, [NotNullWhen(true)] out string? attribute)
		{
			attribute = default;

			if (context.CodeContext is not CodeContext.SourceReference and not CodeContext.Graph)
				return false;

			if (fragment.Classification != ClassificationKind.LineNumber)
				return false;

			if (int.TryParse(fragment.Text, out int line))
			{
				attribute = GetLineLinkAttribute(context, line);
				return true;
			}

			return false;
		}
		public string GetLineLinkAttribute(Context context, int line)
		{
			string id = GetLineId(context, line, context.CodeContext is CodeContext.Graph);
			return $"href=\"#{id}\"";
		}
		public string GetLineDataAttribute(Context context, int line) => $"data-line-number=\"{line}\"";

		public bool TryGetSymbolDataAttribute(Context context, TextFragment fragment, [NotNullWhen(true)] out string? attribute)
		{
			return TryGetSymbolDataAttribute(context, fragment.Symbol, out attribute);
		}
		public bool TryGetSymbolDataAttribute(Context context, ISymbol? symbol, [NotNullIfNotNull(nameof(symbol)), NotNullWhen(true)] out string? attribute)
		{
			if (symbol is null)
			{
				attribute = default;
				return false;
			}

			attribute = $"data-symbol-id=\"{symbol.Id}\"";
			return true;
		}
		#endregion

		#region Helpers
		public IControlFlowBlock GetTarget(Context context, IControlFlowOutgoingBranch branch)
		{
			if (context.Settings.Optimise is false)
				return branch.To;

			IControlFlowBlock to = branch.To;

			while (IncludeBlock(context, to) is false && to.Outgoing.Count is 1)
				to = to.Outgoing[0].To;

			return to;
		}
		#endregion
	}
}

public static class MermaidControlFlowPrinterExtensions
{
	extension(IControlFlowGraph graph)
	{
		#region Methods
		public MermaidControlFlow.Result ToMermaid(MermaidControlFlow.Settings? settings = null)
		{
			settings ??= new();
			MermaidControlFlow.Printer printer = new();
			MermaidControlFlow.Result result = printer.Print(graph, settings);

			return result;
		}
		#endregion
	}
}
