<Project Sdk="Microsoft.NET.Sdk">

	<!-- Project -->
	<PropertyGroup Label="project">
		<TargetFrameworks>net10.0</TargetFrameworks>
		<LangVersion>14</LangVersion>
		<Nullable>enable</Nullable>

		<AssemblyName>OwlDomain.Owl.LSP</AssemblyName>
		<RootNamespace>OwlDomain.Owl.LSP</RootNamespace>

		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<Deterministic>true</Deterministic>

		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

		<IsAotCompatible Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net7.0'))">true</IsAotCompatible>
		<IsTrimmable Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">true</IsTrimmable>
	</PropertyGroup>

	<!-- Project references -->
	<ItemGroup Label="projects">
		<ProjectReference Include="../../code/Code/Code.csproj" />
	</ItemGroup>

	<!-- Package references -->
	<ItemGroup Label="packages">
		<PackageReference Include="EmmyLua.LanguageServer.Framework" Version="0.9.2" />
	</ItemGroup>

</Project>
