using System.CodeDom.Compiler;

namespace OwlDomain.ParsingTools.Generator;

internal static class IndentedTextWriterExtensions
{
	#region Nested types
	public readonly struct BraceScope(IndentedTextWriter writer) : IDisposable
	{
		public void Dispose()
		{
			writer.Indent--;
			writer.WriteLine("}");
		}
	}
	public readonly struct IndentScope(IndentedTextWriter writer) : IDisposable
	{
		public void Dispose() => writer.Indent--;
	}
	public readonly struct PreambleScope(IndentedTextWriter writer) : IDisposable
	{
		public void Dispose()
		{
			writer.WriteLine("#nullable restore");
		}
	}
	public readonly struct TypeScope(IndentedTextWriter writer) : IDisposable
	{
		public void Dispose()
		{
			writer.WriteLine();
		}
	}
	public readonly struct RegionScope(IndentedTextWriter writer) : IDisposable
	{
		public void Dispose() => writer.WriteLine("#endregion");
	}
	#endregion

	extension(IndentedTextWriter writer)
	{
		#region Scope methods
		public IndentScope Indented()
		{
			writer.Indent++;
			return new(writer);
		}
		public BraceScope Braced()
		{
			writer.WriteLine("{");
			writer.Indent++;

			return new(writer);
		}
		public PreambleScope Preamble(string? @namespace = null)
		{
			writer.WriteLine("// <auto-generated />");
			writer.WriteLine();
			writer.WriteLine("#nullable enable");
			writer.WriteLine();

			WriteFileNamespace(writer, @namespace);

			return new(writer);
		}
		public TypeScope TypePreamble()
		{
			WriteGeneratedAttribute(writer);

			return new(writer);
		}
		public RegionScope Region(string name)
		{
			writer.WriteLine($"#region {name}");

			return new(writer);
		}
		#endregion

		#region Methods
		public void WriteGeneratedAttribute()
		{
			writer.WriteLine("""[GeneratedCode("OwlSyntaxNodeGenerator", "dev")]""");
		}
		public void WriteFileNamespace(string? @namespace)
		{
			if (@namespace is null)
				return;

			writer.WriteLine($"namespace {@namespace};");
			writer.WriteLine();
		}
		public void WriteUsingNamespace(string @namespace)
		{
			writer.WriteLine($"using {@namespace};");
		}
		#endregion
	}
}
