name: .NET CI

permissions:
  contents: read


on:
  workflow_dispatch:
  push:
    branches: '**'
    paths:
      - 'src/**'
      - '.editorconfig'


env:
    DOTNET_NOLOGO: true
    DOTNET_CLI_TELEMETRY_OPTOUT: true
    NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages


jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository.
      uses: actions/checkout@v5
      with:
        sparse-checkout: |
          src/
          .editorconfig

    - name: Setup the .NET development environment.
      uses: actions/setup-dotnet@v5

    - name: Restore the project dependencies.
      working-directory: src/
      run: dotnet restore

    - name: Build the source directory.
      working-directory: src/
      run: dotnet build --no-restore

    - name: Run the linter.
      working-directory: src/
      run: dotnet format --no-restore --verify-no-changes --verbosity diagnostic



  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            src/
            .editorconfig

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5

      - name: Restore the project dependencies.
        working-directory: src/
        run: dotnet restore

      - name: Build the source directory.
        working-directory: src/
        run: dotnet build --no-restore --warnaserror --configuration ${{ matrix.configuration }} /p:ContinuousIntegrationBuild=true /p:noWarn=IDE0055 /p:noWarn=CS1591



  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v5
        with:
          sparse-checkout: |
            src/
            .editorconfig

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5

      - name: Restore the project dependencies.
        working-directory: src/
        run: dotnet restore

      - name: Build the source directory.
        working-directory: src/
        run: dotnet build --no-restore --configuration ${{ matrix.configuration }} /p:ContinuousIntegrationBuild=true /p:noWarn=IDE0055 /p:noWarn=CS1591

      - name: Run the tests.
        working-directory: src/
        run: dotnet test --no-build --configuration ${{ matrix.configuration }} --warnaserror /p:noWarn=IDE0055 /p:noWarn=CS1591



  publish:
    # Only on main and dev
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            target-runtime: linux-x64

          - runner: ubuntu-24.04-arm
            target-runtime: linux-arm64

          #- runner: windows-latest
            #target-runtime: win-x64

          #- runner: windows-11-arm
            #target-runtime: win-arm64

          - runner: macos-latest
            target-runtime: osx-arm64

          - runner: macos-26-intel
            target-runtime: osx-x64

    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v5
        with:
          sparse-checkout: src/

      - name: Setup the .NET development environment.
        uses: actions/setup-dotnet@v5

      - name: Restore the project dependencies.
        working-directory: src/cli/
        run: dotnet restore --runtime ${{ matrix.target-runtime }}

      - name: Build the project directory.
        working-directory: src/cli/
        run: dotnet build --no-restore --warnaserror --configuration Release --runtime ${{ matrix.target-runtime }} /p:ContinuousIntegrationBuild=true /p:noWarn=IDE0055 /p:noWarn=CS1591

      - name: Publish the project.
        working-directory: src/cli/
        run: dotnet publish --no-build  --warnaserror --configuration Release --runtime ${{ matrix.target-runtime }} /p:ContinuousIntegrationBuild=true /p:noWarn=IDE0055 /p:noWarn=CS1591 --output "${{ runner.temp }}/publishing/cli/cli (${{ matrix.target-runtime }})"

      - name: Remove unnecessary files.
        run: rm -f "${{ runner.temp }}/publishing/cli/**.xml"

      - name: Create the archive directory.
        run: mkdir "${{ runner.temp }}/publishing/archives"

      - name: Archive the published artifact.
        working-directory: "${{ runner.temp }}/publishing/archives"
        run: tar -cvzf "owl (${{ matrix.target-runtime }}).tar.gz" "${{ runner.temp }}/publishing/cli/cli (${{ matrix.target-runtime }})"

      - name: Upload published artifact.
        uses: actions/upload-artifact@v7
        with:
          path: "${{ runner.temp }}/publishing/archives/owl (${{ matrix.target-runtime }}).tar.gz"
          name: "owl (${{ matrix.target-runtime }})"
          if-no-files-found: error
          archive: false
